version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ../../public_html:/opt/app-root/src/